version: 2
jobs:

  build:
    macos:
      xcode: "10.2.1"

    shell: "/bin/bash --login -eo pipefail"

    steps:
      - checkout

      - run: 
          name: Run Unit Tests
          command: |
            xcodebuild test \
            -scheme Hello_World \
            -sdk iphonesimulator \
            -destination "platform=IOS Simulator,OS=11.4,name=iPhone 7"

      - run: 
          name: Run Unit Tests
          command: |
            xcodebuild test \
            -scheme Hello_World \
            -sdk iphonesimulator \
            -destination "platform=IOS Simulator,OS=12.2,name=iPhone 7"
