version: 2
jobs:

  # Build the app for testing and persist the build sources
  # to a shared workspace for other jobs to access
  test_build:
    macos:
      xcode: "10.2.1"

    shell: "/bin/bash --login -eo pipefail"

    steps:
      - checkout
    
      - run:
          name: "Setup environment variable"
          command: |
            mkdir DerivedData
            echo 'export DERIVED_DATA_PATH="DerivedData"' >> $BASH_ENV

      - run: bundle install
      - run: bundle exec rake build_for_testing
      
      - run:
          name: Copy Derived Data Folder
          command: |
            mkdir -p /tmp/workspace
            cp -r DerivedData/ /tmp/workspace/

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "**/*"


  test_ios_11:
    macos:
      xcode: "10.2.1"

    shell: "/bin/bash --login -eo pipefail"

    steps:
      - checkout

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: "Setup environment variables"
          command: |
            mkdir DerivedData
            echo 'export DERIVED_DATA_PATH="DerivedData"' >> $BASH_ENV
            echo 'export IOS_VERSION=11.4' >> $BASH_ENV

      - run:
          name: Move build artifacts
          command: cp -r /tmp/workspace/ DerivedData/

      - run: bundle install
      - run: bundle exec rake unit_tests


  test_ios_12:
    macos:
      xcode: "10.2.1"

    shell: "/bin/bash --login -eo pipefail"

    steps:
      - checkout

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: "Setup environment variables"
          command: |
            mkdir DerivedData
            echo 'export DERIVED_DATA_PATH="DerivedData"' >> $BASH_ENV
            echo 'export IOS_VERSION=12.2' >> $BASH_ENV

      - run:
          name: Move build artifacts
          command: cp -r /tmp/workspace/ DerivedData/

      - run: bundle install
      - run: bundle exec rake unit_tests


workflows:
  version: 2

  build_and_test:
    jobs:
      - test_build 
      
      - test_ios_11:
          requires:
            - test_build

      - test_ios_12:
          requires:
            - test_build
