version: 2
jobs:

  test_ios_11:
    macos:
      xcode: "10.2.1"

    shell: "/bin/bash --login -eo pipefail"

    steps:
      - checkout

      - run: 
          name: Run Unit Tests
          command: |
            xcodebuild test \
            -scheme Hello_World \
            -sdk iphonesimulator \
            -destination "platform=IOS Simulator,OS=11.4,name=iPhone 7"

  test_ios_12:
    macos:
      xcode: "10.2.1"

    shell: "/bin/bash --login -eo pipefail"

    steps:
      - checkout

      - run: 
          name: Run Unit Tests
          command: |
            xcodebuild test \
            -scheme Hello_World \
            -sdk iphonesimulator \
            -destination "platform=IOS Simulator,OS=12.2,name=iPhone 7"

workflows:
  version: 2

  test:
    jobs:
      - test_ios_11
      - test_ios_12
